controllerWebsiteCoach:
    resource: ../../src/Infrastructure/Controllers/Website/Coach/
    type: annotation

controllerWebsiteClub:
    resource: ../../src/Infrastructure/Controllers/Website/Club/
    type: annotation

controllerWebsitePlayer:
    resource: ../../src/Infrastructure/Controllers/Website/Player/
    type: annotation

controllerBackOfficeCoach:
    resource: ../../src/Infrastructure/Controllers/BackOffice/Coach/
    type: annotation

controllerBackOfficeClub:
    resource: ../../src/Infrastructure/Controllers/BackOffice/Club/
    type: annotation

controllerBackOfficePlayer:
    resource: ../../src/Infrastructure/Controllers/BackOffice/Player/
    type: annotation

controllerBackOfficeStadium:
    resource: ../../src/Infrastructure/Controllers/BackOffice/Stadium/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
