controllerCoach:
    resource: ../../src/Infrastructure/Controllers/Coach/
    type: annotation

controllerClub:
    resource: ../../src/Infrastructure/Controllers/Club/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
