#COACHES
app_coach:
    path: /coaches
    controller: App\Infrastructure\Controllers\Coach\CoachController::list

app_add_coach:
    path: /addCoach
    controller: App\Infrastructure\Controllers\Coach\CoachController::add

app_add_coach_submit:
    path: /addCoachSubmitAction
    controller: App\Infrastructure\Controllers\Coach\CoachController::addSubmitAction

app_update_coach:
    path: /updateCoach/{coachId}
    controller: App\Infrastructure\Controllers\Coach\CoachController::update

app_remove_coach:
    path: /removeCoachAction
    controller: App\Infrastructure\Controllers\Coach\CoachController::removeSubmitAction

#CLUBS
app_club:
    path: /clubs
    controller: App\Infrastructure\Controllers\Club\ClubController::list

app_add_club:
    path: /addClub
    controller: App\Infrastructure\Controllers\Club\ClubController::add

app_add_club_submit:
    path: /addClubSubmitAction
    controller: App\Infrastructure\Controllers\Club\ClubController::addSubmitAction

app_update_club:
    path: /updateClub/{clubId}
    controller: App\Infrastructure\Controllers\Club\ClubController::update

app_remove_club:
    path: /removeClubAction
    controller: App\Infrastructure\Controllers\Club\ClubController::removeSubmitAction

#PLAYERS
app_player:
    path: /players
    controller: App\Infrastructure\Controllers\Player\PlayerController::list

app_add_player:
    path: /addPlayer
    controller: App\Infrastructure\Controllers\Player\PlayerController::add

app_add_player_submit:
    path: /addPlayerSubmitAction
    controller: App\Infrastructure\Controllers\Player\PlayerController::addSubmitAction

app_remove_player:
    path: /removePlayerAction
    controller: App\Infrastructure\Controllers\Player\PlayerController::removeSubmitAction