#COACHES
app_coach:
    path: /coaches
    controller: App\Infrastructure\Controllers\Coach\CoachController::listingCoaches

app_add_coach:
    path: /addCoach
    controller: App\Infrastructure\Controllers\Coach\CoachController::addCoach

app_add_coach_submit:
    path: /addCoachSubmitAction
    controller: App\Infrastructure\Controllers\Coach\CoachController::addCoachSubmitAction

app_update_coach:
    path: /updateCoach/{coachId}
    controller: App\Infrastructure\Controllers\Coach\CoachController::updateCoach

app_remove_coach:
    path: /removeCoachAction
    controller: App\Infrastructure\Controllers\Coach\CoachController::removeCoachAction

#CLUBS
app_club:
    path: /clubs
    controller: App\Infrastructure\Controllers\Club\ClubController::listingClubs

app_add_club:
    path: /addClub
    controller: App\Infrastructure\Controllers\Club\ClubController::addClub

app_add_club_submit:
    path: /addClubSubmitAction
    controller: App\Infrastructure\Controllers\Club\ClubController::addClubSubmitAction

app_update_club:
    path: /updateClub/{clubId}
    controller: App\Infrastructure\Controllers\Club\ClubController::updateClub