app_coach:
    path: /coaches
    controller: App\Infrastructure\Controllers\CoachController::listingCoaches

app_add_coach:
    path: /addCoach
    controller: App\Infrastructure\Controllers\CoachController::addCoach

app_add_coach_submit:
    path: /addCoachSubmitAction
    controller: App\Infrastructure\Controllers\CoachController::addCoachSubmitAction

app_update_coach:
    path: /updateCoach/{coachId}
    controller: App\Infrastructure\Controllers\CoachController::updateCoach

app_remove_coach:
    path: /removeCoachAction
    controller: App\Infrastructure\Controllers\CoachController::removeCoachAction
